fix: TER-87 allow invalid in config for saved  and change and get han…
amplience/dc-visualization-sdk pull request #17
Opened 2021-05-25 10:50 UTC by dev-warner

…dlers

## Pull request checklist

Please check if your PR fulfils the following requirements:

- [x] Code has been written in project defined style (`npm run lint`).
- [x] Tests (`npm test`) for the changes have been added (for bug fixes / features).
- [x] PR title and git commit messages conform to the [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) specification.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Invalid content doesnt trigger change

## What is the new behavior?

allow config option to allow invalid content

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2021-05-25 14:13 UTC, pixelscript requested changes

2021-05-25 14:13 UTC, pixelscript commented on README.md
> +| `allowInvalid` | Whether or not to allow invalid content to be returned on change. i.e minItems requirements being ignored | `true, false`           | `false`     |
i.e. should be e.g.

2021-06-14 09:09 UTC, pixelscript approved these changes

2021-06-14 10:32 UTC, Benj0s approved these changes

2021-06-14 10:35 UTC, programmerinprogress approved these changes

2021-06-15 12:57 UTC, merged